Update docs-only-pipeline.yaml

diff --git a/.tekton/docs-only-pipeline.yaml b/.tekton/docs-only-pipeline.yaml
--- a/.tekton/docs-only-pipeline.yaml
+++ b/.tekton/docs-only-pipeline.yaml
@@ -19,4 +19,5 @@ spec:
               script: |
                 #!/bin/sh
                 echo "✅ Docs pipeline running!"
-                echo "This should ONLY run when docs/ files change"
+                echo "failing pipeline"
+                exit 1
